from pathlib import Path

path = Path('AgentPanelSpeaker/TranscriptView.cs')
text = path.read_text(encoding='utf-8-sig')
old = '''  public void ApplySettings(TranscriptSettings settings, bool dark)\n  {\n    LogViewState("apply-settings", "begin", requestedDark: dark);\n    _settings = settings.Normalize();\n    _virtualDocument?.SetShowRolledBackHistory(\n      _settings.ShowRolledBackHistory);\n    _dark = dark;\n    Color page = dark\n      ? Color.FromArgb(30, 32, 35)\n      : Color.FromArgb(247, 247, 245);\n    Color text = dark\n      ? Color.FromArgb(217, 220, 225)\n      : Color.FromArgb(36, 38, 41);\n    LogLoadingLabelNativeState("apply-settings", "before-back-color");\n    _loadingLabel.BackColor = page;\n    LogLoadingLabelNativeState("apply-settings", "after-back-color");\n    _loadingLabel.ForeColor = text;\n    LogLoadingLabelNativeState("apply-settings", "after-fore-color");\n    _failureLabel.BackColor = page;\n    _failureLabel.ForeColor = text;\n    if (_initialized)\n    {\n      QueueSettingsApply(immediate: false);\n    }\n    LogViewState("apply-settings", "end", requestedDark: dark);\n  }\n'''
new = '''  public void ApplySettings(TranscriptSettings settings, bool dark)\n  {\n    LogViewState("apply-settings", "begin", requestedDark: dark);\n    TranscriptSettings normalized = settings.Normalize();\n    bool followEnabled = !_settings.FollowSpeech && normalized.FollowSpeech;\n    TranscriptPlaybackPosition? reattachPosition = null;\n    if (followEnabled)\n    {\n      if (_pendingPosition is TranscriptPlaybackPosition current &&\n          current.NodeId > 0 &&\n          current.State is TranscriptPlaybackState.Speaking or\n            TranscriptPlaybackState.Paused)\n      {\n        reattachPosition = current;\n      }\n      else if (_pendingPosition is null)\n      {\n        reattachPosition = _lastLocatedContentPosition;\n      }\n    }\n\n    _settings = normalized;\n    _virtualDocument?.SetShowRolledBackHistory(\n      _settings.ShowRolledBackHistory);\n    _dark = dark;\n    Color page = dark\n      ? Color.FromArgb(30, 32, 35)\n      : Color.FromArgb(247, 247, 245);\n    Color text = dark\n      ? Color.FromArgb(217, 220, 225)\n      : Color.FromArgb(36, 38, 41);\n    LogLoadingLabelNativeState("apply-settings", "before-back-color");\n    _loadingLabel.BackColor = page;\n    LogLoadingLabelNativeState("apply-settings", "after-back-color");\n    _loadingLabel.ForeColor = text;\n    LogLoadingLabelNativeState("apply-settings", "after-fore-color");\n    _failureLabel.BackColor = page;\n    _failureLabel.ForeColor = text;\n    if (_initialized)\n    {\n      QueueSettingsApply(immediate: followEnabled);\n    }\n    if (reattachPosition is not null)\n    {\n      ShowPlaybackPosition(reattachPosition);\n    }\n    LogViewState("apply-settings", "end", requestedDark: dark);\n  }\n'''
count = text.count(old)
if count != 1:
  raise SystemExit(f'Issue #57 ApplySettings anchor matched {count} times')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
